name: Render and Deploy ArgoCD to KIND

on:
  push:
    branches:
      - main
    paths:
      - 'apps/argocd/base/application.yaml'
      - 'apps/argocd/overlays/dev/values.yaml'
  workflow_dispatch:

jobs:
  render-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We'll configure credentials manually

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Ensure overlays/dev directory exists
        run: mkdir -p apps/argocd/overlays/dev

      - name: Generate rendered ArgoCD manifests
        run: |
          kubectl kustomize --enable-helm --load-restrictor LoadRestrictionsNone apps/argocd/overlays/dev > apps/argocd/overlays/dev/_rendered_argocd.yaml

      - name: Copy rendered file to _rendered_argocd_latest.yaml
        run: cp apps/argocd/overlays/dev/_rendered_argocd.yaml apps/argocd/overlays/dev/_rendered_argocd_latest.yaml

      - name: Commit and push _rendered_argocd_latest.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add apps/argocd/overlays/dev/_rendered_argocd_latest.yaml
          git commit -m "Update _rendered_argocd_latest.yaml from workflow [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Apply rendered ArgoCD manifests
        run: |
          kubectl apply -f apps/argocd/overlays/dev/_rendered_argocd.yaml
